/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mmtimehistory;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;


/**
 *
 * @author Home-dev
 */
public class InterfazP extends javax.swing.JFrame {

    /**
     * Creates new form InterfazP
     */
    public InterfazP() {
        initComponents();
        this.setLocationRelativeTo(null);
        mostrarFecha();
        mostrarHora();
    }
    
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icono3.png"));
        return retValue;
    }
    
    void mostrarFecha(){
        SimpleDateFormat s = new SimpleDateFormat("dd/MM/yy");
        Date d = new Date();
        fecha.setText(s.format(d)); 
        
        
    }
    
    void mostrarHora(){
        new Timer (0, new ActionListener(){
            public void actionPerformed(ActionEvent e){
                SimpleDateFormat s = new SimpleDateFormat("hh:mm a");
                Date d = new Date();
                hora.setText(s.format(d));
            }            
        }).start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        jLabelHoraInicio = new javax.swing.JLabel();
        jLabelHoraFin = new javax.swing.JLabel();
        horaInicio = new javax.swing.JTextField();
        horaFin = new javax.swing.JTextField();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(204, 102, 255));
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 780, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        fecha.setFont(new java.awt.Font("Gabriola", 1, 48)); // NOI18N
        fecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 160, 50));

        hora.setFont(new java.awt.Font("Gabriola", 1, 36)); // NOI18N
        hora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 140, 50));

        jLabelHoraInicio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelHoraInicio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelHoraInicio.setText("Hora inicio: ");
        getContentPane().add(jLabelHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));

        jLabelHoraFin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelHoraFin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelHoraFin.setText("Hora Fin:");
        getContentPane().add(jLabelHoraFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, -1, -1));

        horaInicio.setText("valor");
        getContentPane().add(horaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 60, -1));

        horaFin.setText("valor");
        getContentPane().add(horaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 60, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_pintuda_rosada.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 763, 836));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazP().setVisible(true);
            }
        });
        
        
        MMTimeHistory TH = new MMTimeHistory();
        TH.main();   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel hora;
    private javax.swing.JTextField horaFin;
    private javax.swing.JTextField horaInicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelHoraFin;
    private javax.swing.JLabel jLabelHoraInicio;
    // End of variables declaration//GEN-END:variables
}
